
2022-11-25 10:09:25 --------------------------------------------------
Traceback (most recent call last):File "E:\HuaHuoLabel_new\need\main.py", line 264, in add_to_trainff = QIcon(10)TypeError:'PySide6.QtGui.QIcon.__init__' called with wrong argument types:
  PySide6.QtGui.QIcon.__init__(int)
Supported signatures:
  PySide6.QtGui.QIcon.__init__()
  PySide6.QtGui.QIcon.__init__(PySide6.QtGui.QIconEngine)
  PySide6.QtGui.QIcon.__init__(str)
  PySide6.QtGui.QIcon.__init__(Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap])
  PySide6.QtGui.QIcon.__init__(Union[PySide6.QtGui.QPixmap, PySide6.QtGui.QImage, str])

2022-11-25 10:10:34 --------------------------------------------------
Main window initiated.

2022-11-25 10:10:36 --------------------------------------------------
Traceback (most recent call last):File "E:\HuaHuoLabel_new\need\main.py", line 264, in add_to_trainff = QIcon(10)TypeError:'PySide6.QtGui.QIcon.__init__' called with wrong argument types:
  PySide6.QtGui.QIcon.__init__(int)
Supported signatures:
  PySide6.QtGui.QIcon.__init__()
  PySide6.QtGui.QIcon.__init__(PySide6.QtGui.QIconEngine)
  PySide6.QtGui.QIcon.__init__(str)
  PySide6.QtGui.QIcon.__init__(Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap])
  PySide6.QtGui.QIcon.__init__(Union[PySide6.QtGui.QPixmap, PySide6.QtGui.QImage, str])

2022-11-25 10:11:37 --------------------------------------------------
Main window initiated.

2022-11-25 10:11:39 --------------------------------------------------
Traceback (most recent call last):File "E:\HuaHuoLabel_new\need\main.py", line 264, in add_to_trainff = QIcon(10)TypeError:'PySide6.QtGui.QIcon.__init__' called with wrong argument types:
  PySide6.QtGui.QIcon.__init__(int)
Supported signatures:
  PySide6.QtGui.QIcon.__init__()
  PySide6.QtGui.QIcon.__init__(PySide6.QtGui.QIconEngine)
  PySide6.QtGui.QIcon.__init__(str)
  PySide6.QtGui.QIcon.__init__(Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap])
  PySide6.QtGui.QIcon.__init__(Union[PySide6.QtGui.QPixmap, PySide6.QtGui.QImage, str])

2022-11-25 10:15:16 --------------------------------------------------
Main window initiated.

2022-11-25 10:15:17 --------------------------------------------------
Traceback (most recent call last):File "E:\HuaHuoLabel_new\need\main.py", line 264, in add_to_trainff = QIcon(10)TypeError:'PySide6.QtGui.QIcon.__init__' called with wrong argument types:
  PySide6.QtGui.QIcon.__init__(int)
Supported signatures:
  PySide6.QtGui.QIcon.__init__()
  PySide6.QtGui.QIcon.__init__(PySide6.QtGui.QIconEngine)
  PySide6.QtGui.QIcon.__init__(str)
  PySide6.QtGui.QIcon.__init__(Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap])
  PySide6.QtGui.QIcon.__init__(Union[PySide6.QtGui.QPixmap, PySide6.QtGui.QImage, str])

2022-11-25 10:18:31 --------------------------------------------------
Main window initiated.

2022-11-25 11:04:39 --------------------------------------------------
Application opened.

2022-11-25 11:07:21 --------------------------------------------------
Application closed.

2022-11-25 11:08:20 --------------------------------------------------
Application opened.

2022-11-25 11:08:56 --------------------------------------------------
Application closed.

2022-11-25 11:13:04 --------------------------------------------------
Application opened.

2022-11-25 11:14:10 --------------------------------------------------
Application closed.

2022-11-25 11:16:40 --------------------------------------------------
Application opened.

2022-11-25 11:17:07 --------------------------------------------------
Application closed.

2022-11-25 11:17:21 --------------------------------------------------
Application opened.

2022-11-25 11:17:37 --------------------------------------------------
Application closed.

2022-11-25 17:20:04 --------------------------------------------------
Application opened.

2022-11-25 17:23:05 --------------------------------------------------
Traceback (most recent call last):File "E:\HuaHuoLabel_new\need\main.py", line 463, in button_actionself.go_next_img()File "E:\HuaHuoLabel_new\need\main.py", line 920, in go_next_imgself.show_img_status_info()File "E:\HuaHuoLabel_new\need\main.py", line 1900, in show_img_status_infoself.cv2_img = cv2.imdecode(np.fromfile(path, dtype='uint8'), cv2.IMREAD_COLOR)FileNotFoundError:[Errno 2] No such file or directory: 'E:/HuaHuoLabel_new/待分类图片/单分类/175063258820220210#B#.bmp'

2022-11-25 17:23:37 --------------------------------------------------
Traceback (most recent call last):File "E:\HuaHuoLabel_new\need\main.py", line 247, in keyPressEventself.scan_img(last=True)File "E:\HuaHuoLabel_new\need\main.py", line 1683, in scan_imgself.show_img_status_info()File "E:\HuaHuoLabel_new\need\main.py", line 1900, in show_img_status_infoself.cv2_img = cv2.imdecode(np.fromfile(path, dtype='uint8'), cv2.IMREAD_COLOR)FileNotFoundError:[Errno 2] No such file or directory: 'E:/HuaHuoLabel_new/待分类图片/单分类/175063258820220210#B#.bmp'

2022-11-25 17:23:40 --------------------------------------------------
Traceback (most recent call last):File "E:\HuaHuoLabel_new\need\main.py", line 249, in keyPressEventself.scan_img(next=True)File "E:\HuaHuoLabel_new\need\main.py", line 1691, in scan_imgself.show_img_status_info()File "E:\HuaHuoLabel_new\need\main.py", line 1900, in show_img_status_infoself.cv2_img = cv2.imdecode(np.fromfile(path, dtype='uint8'), cv2.IMREAD_COLOR)FileNotFoundError:[Errno 2] No such file or directory: 'E:/HuaHuoLabel_new/待分类图片/单分类/175063258820220210#B#.bmp'

2022-11-25 17:39:03 --------------------------------------------------
Application closed.
